/* ===== Amex: what is due this month, what is due next month, and the set-aside that keeps the card payable ===== */
const AMX_SRC={typed:'typed by you',pdf:'from the PDF',estimated:'from your entries so far',open:'still building'};
function amexPanel(S){
  const L=amexStatementList(),due=L.filter(s=>s.state==='due'),open=L.find(s=>s.state==='open'),buf=STATE.buffer||0,bank=(STATE.bank||0)+sinceBalance();
  const owed=sum(due,s=>s.total)+(open?open.total:0),mk=ym(parseISO(todayISO()));
  const dueCard=s=>`<div class="amc due"><span class="lbl">${ym(parseISO(s.due))===mk?'Due this month':'Due next month'} · ${fdate(parseISO(s.due))}</span>
    <div class="amtbig">£ ${F('state',`amexStmt.${s.close}.total`,'num',s.src==='estimated'?'':s.total,`style="width:130px" placeholder="${s.calc.toFixed(2)}"`,true)}</div>
    <small>Statement ${fdate(parseISO(s.from))} to ${fdate(parseISO(s.close))}, closed. ${AMX_SRC[s.src]||''}${s.src==='estimated'?' ('+GBP2(s.calc)+')':''}. Type the real total, or <label class="lnk">upload the PDF<input type="file" id="impFile" accept=".pdf,application/pdf,.csv" hidden></label>.</small><div id="impMsg" class="small"></div></div>`;
  const openCard=s=>`<div class="amc"><span class="lbl">${ym(parseISO(s.due))===mk?'Due this month':'Due next month'} · ${fdate(parseISO(s.due))}</span><div class="amtbig">${GBP2(s.total)} <span class="small muted">so far</span></div>
    <small>Statement ${fdate(parseISO(s.from))} to ${fdate(parseISO(s.close))}, still open. ${s.rows.length} purchase${s.rows.length===1?'':'s'}. It grows as you add or upload Amex spending.</small></div>`;
  return`<div class="c12 amxgrid">${due.map(dueCard).join('')}${open?openCard(open):''}${!due.length?'<div class="amc"><span class="lbl">Nothing due yet</span><div class="amtbig">£0</div><small>No closed statement is waiting to be paid.</small></div>':''}</div>
   <div class="panel c12"><div class="row" style="justify-content:space-between"><h2>Set aside for the Amex</h2><span class="small muted">Never spend this. It is already spoken for.</span></div>
    <div class="strip" style="grid-template-columns:1fr auto 1fr auto 1fr"><div class="c"><span class="lbl">In the bank</span><b>${GBP(bank)}</b></div><span class="op">−</span><div class="c"><span class="lbl">Set aside for Amex</span><b>${GBP(owed)}</b></div><span class="op">=</span><div class="c res ${bank-owed<0?'neg':bank-owed<buf?'tight':'pos'}"><span class="lbl">Really yours</span><b>${GBP(bank-owed)}</b></div></div>
    <p class="small ink2" style="margin:10px 0 0">Your ${GBP(buf)} buffer sits on top, so the bank should never fall below <b>${GBP(owed+buf)}</b>. ${S.lowTrue&&S.lowTrue.v<buf?`<b class="neg">The forecast breaks this on ${fdate(S.lowTrue.t)}: the bank would be ${GBP(buf-S.lowTrue.v)} short.</b>`:`<b class="pos">The forecast keeps it, with at least ${GBP(S.lowTrue?S.lowTrue.v-buf:0)} to spare.</b>`}</p></div>`}
function amexStatementsTable(){
  const L=amexStatementList().slice().reverse();
  return`<div class="tblwrap"><table><thead><tr><th>Statement</th><th>Leaves the bank</th><th class="n">Purchases</th><th class="n">Total</th><th></th></tr></thead><tbody>${L.map(s=>{const op=view.open['amx_'+s.close];
   return`<tr><td><b>${fdate(parseISO(s.from))} to ${fdate(parseISO(s.close))}</b></td><td>${fdate(parseISO(s.due))}</td><td class="n">${s.rows.length}</td><td class="n"><b>${GBP2(s.total)}</b></td><td>${s.state==='paid'?'<span class="pill good">paid</span>':s.state==='due'?(s.total>0.005?'<span class="pill warn">to pay</span>':'<span class="pill good">nothing to pay</span>'):'<span class="pill info">open</span>'} <button class="btn ghost sm" data-act="toggle" data-v="amx_${s.close}">${op?'Hide':'Show'}</button></td></tr>
   ${op?`<tr><td colspan="5" style="padding:0 0 6px 16px"><table><tbody>${s.rows.map(t=>`<tr><td style="width:70px" class="muted small">${fdate(parseISO(t.d))}</td><td>${esc(cleanD(t.t).toLowerCase().replace(/\\b[a-z]/g,c=>c.toUpperCase()).slice(0,40))}${t.note&&t.note!==t.t?`<span class="small muted" style="display:block;font-style:italic">${esc(t.note)}</span>`:''}</td><td class="muted small">${esc(rvLabel(t))}</td><td class="n">${t.a<0?'':'−'}${GBP2(Math.abs(t.a))}</td></tr>`).join('')||'<tr><td class="muted small">No joint purchases.</td></tr>'}</tbody></table></td></tr>`:''}`}).join('')}</tbody></table></div>
   <p class="small muted" style="margin:8px 0 0">A purchase counts in your budget on the day you buy it. The whole statement leaves the bank on its due date. Only Annalisa's card is counted.</p>`}
function amexTile(S){
  const L=amexStatementList(),due=L.filter(s=>s.state==='due'),open=L.find(s=>s.state==='open'),owed=sum(due,s=>s.total)+(open?open.total:0),buf=STATE.buffer||0,ok=!(S.lowTrue&&S.lowTrue.v<buf);
  return`<div class="kpi" ${ok?'':'style="border-color:var(--bad)"'}><span>Set aside for Amex</span><b>${GBP(owed)}</b><small><span class="pill ${ok?'good':'bad'}">${ok?'Covered':'Bank would fall short'}</span><br>${due.map(s=>GBP(s.total)+' due '+fdate(parseISO(s.due))).join(' · ')}${due.length&&open?' · ':''}${open?GBP(open.total)+' due '+fdate(parseISO(open.due))+' (so far)':''}</small></div>`}
/* put Niamh's car insurance and her payback under Kids, and keep the real yearly car insurance as a bill */
function fixAdmiral(){let any=false;Object.keys(TX).forEach(m=>{let ch=false;(TX[m]||[]).forEach(t=>{if(t.af)return;t.af=1;
  if(/ADMIRAL MOTO/i.test(t.t||'')&&t.c!=='v_kids'){t.c='v_kids';t.sc=undefined;t.why="Niamh's car insurance: paid up front, she pays back";ch=true}});if(ch){saveTx(m);any=true}});if(any)invalidate();return any}
