/* ===== Budgets: everything you plan, edited as a draft and saved from a chosen month ===== */
function vBudgets(){
  const p=draft(),P=p;
  const inc=sum(p.income,i=>i.amount),monthly=p.bills.map((b,i)=>({b,i})).filter(x=>(x.b.freq||'monthly')==='monthly'),yearly=p.bills.map((b,i)=>({b,i})).filter(x=>(x.b.freq||'monthly')!=='monthly');
  const xcat=new Set((p.transfers||[]).map(x=>x.catId));
  const sBills=sum(monthly,x=>x.b.amount),sY=sum(yearly,x=>x.b.amount/(x.b.freq==='quarterly'?3:12)),sDebt=sum(p.debts,d=>(d.pay||0)+(d.extra||0)),sVar=sum(p.vars.filter(v=>!xcat.has(v.id)),v=>v.budget),sX=sum(p.transfers||[],x=>x.amount),sSav=p.savings.monthly;
  const tot=sBills+sY+sDebt+sVar+sX+sSav,left=inc-tot;
  const w=v=>Math.max(0,v/Math.max(inc,tot)*100);
  const MONSEL=m=>SEL('plan','',m,MON.map((x,i)=>[i+1,x]),'num');
  const row=(x)=>x;
  return draftBar()+intro('Everything you plan to receive and spend, in one place, laid out like your sheet: money in, fixed bills ("standard expenses"), variable spending ("recurring but different each time"), yearly bills and transfers. Edit, then press Save plan. The change starts from the month you choose and past months keep the plan they had.')+`
  <div class="grid">
   <div class="panel c12"><h2>Every £ of your monthly income</h2>
    <div class="split"><span style="background:var(--need);width:${w(sBills)}%" title="Fixed bills"></span><span style="background:var(--need);opacity:.5;width:${w(sY)}%" title="Yearly bills, per month"></span><span style="background:var(--debt);width:${w(sDebt)}%" title="Debts"></span><span style="background:var(--want);width:${w(sVar)}%" title="Variable spending"></span><span style="background:var(--want);opacity:.55;width:${w(sX)}%" title="Transfers"></span><span style="background:var(--save);width:${w(sSav)}%" title="Savings"></span><span style="background:var(--surface2);flex:1" title="Left over"></span></div>
    <div class="legend"><span><b class="sw" style="background:var(--need)"></b>Fixed bills ${GBP(sBills)}</span><span><b class="sw" style="background:var(--need);opacity:.5"></b>Yearly bills, per month ${GBP(sY)}</span><span><b class="sw" style="background:var(--debt)"></b>Debts ${GBP(sDebt)}</span><span><b class="sw" style="background:var(--want)"></b>Variable spending ${GBP(sVar)}</span><span><b class="sw" style="background:var(--want);opacity:.55"></b>Transfers ${GBP(sX)}</span><span><b class="sw" style="background:var(--save)"></b>Savings ${GBP(sSav)}</span><span><b class="sw" style="background:var(--surface2)"></b>Left over ${GBP(left)} of ${GBP(inc)}</span></div>
    <p class="small muted" style="margin-bottom:0">Yearly bills here are shown as one twelfth a month for the picture only. In the forecast they come out when due, unless you choose to spread them.</p></div>
   <div class="panel c12"><h2>Money in</h2><div class="tblwrap"><table><thead><tr><th>Who</th><th class="n">£ per month</th><th class="n">Pay day</th><th>Varies?</th><th></th></tr></thead><tbody>${p.income.map((x,i)=>`<tr><td>${F('plan',`income.${i}.name`,'str',x.name)}</td><td class="n">${F('plan',`income.${i}.amount`,'num',x.amount)}</td><td class="n">${F('plan',`income.${i}.day`,'num',x.day,'min="1" max="31" style="width:60px"')}</td><td style="text-align:center">${F('plan',`income.${i}.varies`,'bool',x.varies)}</td><td>${delBtn('plan','income',i)}</td></tr>`).join('')}</tbody></table></div>
    <div class="row" style="margin-top:8px"><button class="btn ghost sm" data-act="add" data-list="income">+ Add income</button><span class="small muted">Wages land within 3 days of month end, so the forecast uses the day shown. Cash income is logged on the Cash and bank tab.</span></div></div>
   <div class="panel c12"><h2>Fixed bills <span class="muted small">${GBP2(sBills)} a month · the same each month</span></h2><div class="tblwrap"><table><thead><tr><th>Bill</th><th class="n">£</th><th class="n">Day</th><th>Need or want</th><th>Amount</th><th>Match word</th><th style="text-align:center">On Amex</th><th></th></tr></thead><tbody>${monthly.map(({b,i})=>`<tr><td>${F('plan',`bills.${i}.name`,'str',b.name)}${b.guess?'<span class="ex" title="This day is not on your sheet, please check">CHECK DAY</span>':''}</td><td class="n">${F('plan',`bills.${i}.amount`,'num',b.amount)}</td><td class="n">${F('plan',`bills.${i}.day`,'num',b.day,'min="1" max="31" style="width:60px"')}</td><td>${KSEL('plan',`bills.${i}.kind`,b.kind||'need')}</td><td>${SEL('plan',`bills.${i}.variable`,b.variable?'1':'0',[['0','Fixed'],['1','Variable']],'flag')}</td><td>${F('plan',`bills.${i}.match`,'str',b.match||'','style="width:100px" placeholder="on statement"')}</td><td style="text-align:center">${F('plan',`bills.${i}.card`,'bool',b.card)}</td><td>${delBtn('plan','bills',i)}</td></tr>`).join('')}</tbody></table></div>
    <div class="row" style="margin-top:8px"><button class="btn ghost sm" data-act="add" data-list="bills">+ Add bill</button><span class="small muted">"Variable" bills show in Coming up even when small. The match word is part of how it appears on your bank statement, so a payment can be marked Paid. Mortgage, loans and the tax plan are on the Debts tab.</span></div></div>
   <div class="panel c12" style="border-color:var(--good)"><h2>Yearly and irregular bills <span class="muted small">${GBP(sum(yearly,x=>x.b.amount*(x.b.freq==='quarterly'?4:1)))} a year</span></h2>
    <p class="small ink2" style="margin-top:0">Bills that don't come out monthly: home and car insurance, car tax, breakdown cover. Choose how often and which month. By default each is paid from the bank when it falls due. You can instead spread the cost across the year.</p>
    ${yearly.length?`<div class="tblwrap"><table><thead><tr><th>Bill</th><th class="n">£</th><th>How often</th><th>Month</th><th class="n">Day</th><th>How to fund it</th><th style="text-align:center">On Amex</th><th></th></tr></thead><tbody>${yearly.map(({b,i})=>`<tr><td>${F('plan',`bills.${i}.name`,'str',b.name)}</td><td class="n">${F('plan',`bills.${i}.amount`,'num',b.amount)}</td><td>${SEL('plan',`bills.${i}.freq`,b.freq,[['yearly','Every year'],['quarterly','Every 3 months']])}</td><td>${SEL('plan',`bills.${i}.month`,b.month||12,MON.map((x,j)=>[j+1,x]),'num')}</td><td class="n">${F('plan',`bills.${i}.day`,'num',b.day,'min="1" max="31" style="width:60px"')}</td><td>${SEL('plan',`bills.${i}.spread`,b.spread?'1':'0',[['0','Pay from bank when due'],['1','Spread over the year']],'flag')}</td><td style="text-align:center">${F('plan',`bills.${i}.card`,'bool',b.card)}</td><td>${delBtn('plan','bills',i)}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">None yet. Add home insurance, car insurance and anything else that comes out once or a few times a year.</p>'}
    <div class="row" style="margin-top:8px"><button class="btn ghost sm" data-act="add" data-list="yearly">+ Add a yearly bill</button></div></div>
   <div class="panel c12"><h2>Variable spending <span class="muted small">${GBP2(sVar)} a month · recurring but different each time</span></h2><div class="tblwrap"><table><thead><tr><th>Category</th><th class="n">Budget £</th><th>Need or want</th><th style="text-align:center">Can go on card</th><th></th></tr></thead><tbody>${p.vars.map((v,i)=>xcat.has(v.id)?'':`<tr><td>${F('plan',`vars.${i}.name`,'str',v.name)}</td><td class="n">${F('plan',`vars.${i}.budget`,'num',v.budget)}</td><td>${KSEL('plan',`vars.${i}.kind`,v.kind||'want')}</td><td style="text-align:center">${F('plan',`vars.${i}.cardOK`,'bool',v.cardOK)}</td><td>${delBtn('plan','vars',i)}</td></tr>`).join('')}</tbody></table></div>
    <div class="row" style="margin-top:8px"><button class="btn ghost sm" data-act="add" data-list="vars">+ Add category</button><span class="small muted">A budget of £0 means the category is tracked but not limited. Your own categories from the sheet are listed; changes are kept by month.</span></div></div>
   <div class="panel c12"><h2>Transfers to personal accounts <span class="muted small">${GBP2(sX)} a month</span></h2><div class="tblwrap"><table><thead><tr><th>To</th><th class="n">£ per month</th><th>When it goes out</th><th class="n">Day</th></tr></thead><tbody>${(p.transfers||[]).map((x,i)=>`<tr><td>${F('plan',`transfers.${i}.name`,'str',x.name)}</td><td class="n">${F('plan',`transfers.${i}.amount`,'num',x.amount)}</td><td>${SEL('plan',`transfers.${i}.rule`,x.rule,[['afterpay','2 days after wages land'],['day','A set day']])}</td><td class="n">${x.rule==='day'?F('plan',`transfers.${i}.day`,'num',x.day,'min="1" max="31" style="width:60px"'):''}</td></tr>`).join('')}</tbody></table></div>
    <p class="small muted" style="margin-bottom:0">The timing depends, so the plan assumes two days after wages. When the real transfer shows in your bank file, the real date is used.</p></div>
   <div class="panel c12"><h2>One-off expenses</h2><div class="tblwrap"><table><thead><tr><th>What</th><th class="n">£</th><th>Date</th><th>Paid from</th><th></th></tr></thead><tbody>${(p.oneoffs||[]).map((x,i)=>`<tr><td>${F('plan',`oneoffs.${i}.name`,'str',x.name)}</td><td class="n">${F('plan',`oneoffs.${i}.amount`,'num',x.amount)}</td><td>${F('plan',`oneoffs.${i}.date`,'date',x.date)}</td><td>${SEL('plan',`oneoffs.${i}.pay`,x.pay,[['bank','Bank'],['amex','Amex'],['savings','From savings']])}</td><td>${delBtn('plan','oneoffs',i)}</td></tr>`).join('')||'<tr><td colspan="5" class="muted">None yet.</td></tr>'}</tbody></table></div>
    <div class="row" style="margin-top:8px"><button class="btn ghost sm" data-act="add" data-list="oneoffs">+ Add a one-off</button><span class="small muted">For costs you haven't saved towards. Holidays and tax have their own tabs.</span></div></div>
  </div>`}
function addToDraft(l){
  const p=draft(),id=l[0]+'_'+uid();
  if(l==='income')p.income.push({id,name:'New income',amount:0,day:28});
  if(l==='bills')p.bills.push({id,name:'New bill',amount:0,day:1,kind:'need',freq:'monthly',match:''});
  if(l==='yearly')p.bills.push({id,name:'New yearly bill',amount:0,day:1,month:12,kind:'need',freq:'yearly',spread:false,match:''});
  if(l==='vars')p.vars.push({id:'v_'+uid(),name:'New category',budget:0,kind:'want',cardOK:true});
  if(l==='oneoffs')p.oneoffs.push({id,name:'New expense',amount:0,date:addDays(todayISO(),30),pay:'bank'});
  if(l==='debts')p.debts.push({id:'d_'+uid(),name:'New debt',type:'loan',pay:0,day:1,apr:null,extra:0});
  if(l==='tax')p.tax.push({id:'tx_'+uid(),name:'New tax bill',last:null,adj:100,date:addDays(todayISO(),180)});
  if(l==='goals')p.goals.push({id:'g_'+uid(),name:'New holiday or goal',kind:'holiday',target:1000,date:addDays(todayISO(),180),monthly:0,amex:false})}
