/* ===== Debts, Goals and holidays, Tax, Amex ===== */
function vDebts(){
  const p=draft(),S=fc();
  const live=p.debts.map((d,i)=>({d,i,bal:STATE.debtBal[d.id],a:amort(STATE.debtBal[d.id],d.apr,d.pay,d.extra,0,-1)}));
  const totBal=sum(live,x=>x.bal||0),totPay=sum(p.debts,d=>(d.pay||0)+(d.extra||0));
  const known=live.filter(x=>x.a&&x.a.n!=null),last=known.length?Math.max(...known.map(x=>x.a.n)):null;
  const aprs=live.filter(x=>x.bal>0&&x.d.apr>0).sort((a,b)=>b.d.apr-a.d.apr);
  const cards=live.map(({d,i,bal,a})=>{const start=STATE.debtStart[d.id],log=STATE.debtLog[d.id]||[],prog=start&&bal!=null?Math.min(100,Math.max(0,(1-bal/start)*100)):0;
    const end=a&&a.n!=null?addMonthsT(parseISO(STATE.asOf),a.n):null;
    return`<div class="panel c6"><div class="row" style="justify-content:space-between"><h3>${esc(d.name)}</h3><span class="pill info">${d.type==='mortgage'?'Mortgage':d.type==='tax'?'Tax':'Loan'}</span></div>
     ${d.note?`<p class="small ink2" style="margin:4px 0 0">${esc(d.note)}</p>`:''}
     ${bal!=null?`<div class="big" style="margin:6px 0">${GBP(bal)}</div><div class="bar"><i class="g" style="width:${prog}%"></i></div><div class="small muted" style="margin:4px 0 8px">${start?pct(prog)+' paid off of '+GBP(start):'Set a starting balance to track progress'}</div>`:`<p class="muted small">Add the balance left to see the end date and progress.</p>`}
     <div class="list"><div class="item"><span>Monthly payment</span><b>${GBP2((d.pay||0)+(d.extra||0))} on the ${ord(d.day)}</b></div><div class="item"><span>Interest rate</span><b>${d.apr==null?'add rate':d.apr+'%'}</b></div>
      <div class="item"><span>Debt free</span><b>${end?fmonthT(end)+' ('+ys(a.n)+')':a&&a.n==null?'payment too low':'add balance'}</b></div><div class="item"><span>Interest still to pay</span><b>${a&&a.int!=null?GBP(a.int):'–'}</b></div></div>
     ${a&&a.ser.length>1?`<div style="margin-top:8px">${spark(a.ser.filter((_,j)=>j%Math.max(1,Math.floor(a.ser.length/60))===0),'var(--debt)')}<div class="small muted">Balance from now until paid off</div></div>`:''}
     <div class="row" style="margin-top:10px"><label class="small">Balance today £ ${F('state',`debtBal.${d.id}`,'num',bal,'style="width:120px"',true)}</label><button class="btn ghost sm" data-act="testdebt" data-id="${d.id}">Test a lump sum or overpayment</button></div>
     <div class="row" style="margin-top:8px;gap:8px 14px"><label class="small">Monthly payment £ ${F('plan',`debts.${i}.pay`,'num',d.pay,'style="width:90px"')}</label><label class="small">Interest rate % ${F('plan',`debts.${i}.apr`,'num',d.apr,'style="width:70px" placeholder="?"',true)}</label><label class="small" title="Ask your lender. Leave at 0 if there is none">Early repayment charge % ${F('plan',`debts.${i}.erc`,'num',d.erc||0,'style="width:70px"')}</label></div>
     ${bal>0?(()=>{const fee=bal*((d.erc||0)/100),intl=a&&a.int!=null?a.int:null;return`<div class="note" style="margin-top:8px"><b>Pay it all off today:</b> ${GBP(bal+fee)}${fee>0?` (${GBP(bal)} plus a ${GBP(fee)} charge)`:' with no charge entered'}. ${intl!=null?`That saves ${GBP(intl)} of interest${fee>0?`, so you are ${intl-fee>=0?GBP(intl-fee)+' better off':GBP(fee-intl)+' worse off'} after the charge`:''}.`:'Add the rate and payment to see the interest saved.'}</div>`})():''}
     ${log.length>1?`<div class="small muted" style="margin-top:6px">History: ${log.slice(-4).map(x=>fdate(parseISO(x.d))+' '+GBP(x.b)).join(' · ')}</div>`:''}</div>`}).join('');
  return draftBar()+intro('Everything you owe in one place. Type the balance from your latest statement whenever you check it: each update is kept as history, and the end date and interest recalculate.')+`
  <div class="kpis"><div class="kpi"><span>Total owed</span><b>${GBP(totBal)}</b><small>across ${live.filter(x=>x.bal>0).length} debts with balances</small></div><div class="kpi"><span>Paid out each month</span><b>${GBP(totPay)}</b><small>mortgage, loans and tax plan</small></div>
   <div class="kpi"><span>Fully debt free</span><b>${last!=null?fmonthT(addMonthsT(parseISO(STATE.asOf),last)):'–'}</b><small>${last!=null?ys(last)+' from now':'add balances and rates'}</small></div>
   <div class="kpi"><span>Costs you most</span><b style="font-size:1.25rem">${aprs[0]?esc(aprs[0].d.name):'–'}</b><small>${aprs[0]?aprs[0].d.apr+'% interest. Extra cash saves the most here first.':'add interest rates to rank them'}</small></div></div>
  <div class="grid">${cards}
   <div class="panel c12"><h2>Edit debts</h2><div class="tblwrap"><table><thead><tr><th>Debt</th><th>Type</th><th class="n">Starting balance £</th><th class="n">Interest %</th><th class="n">Monthly payment £</th><th class="n">Extra each month £</th><th class="n">Pay day</th><th></th></tr></thead><tbody>
   ${p.debts.map((d,i)=>`<tr><td>${F('plan',`debts.${i}.name`,'str',d.name)}</td><td>${SEL('plan',`debts.${i}.type`,d.type,[['mortgage','Mortgage'],['loan','Loan'],['tax','Tax']])}</td><td class="n">${F('state',`debtStart.${d.id}`,'num',STATE.debtStart[d.id],'',true)}</td><td class="n">${F('plan',`debts.${i}.apr`,'num',d.apr,'style="width:70px"',true)}</td><td class="n">${F('plan',`debts.${i}.pay`,'num',d.pay)}</td><td class="n">${F('plan',`debts.${i}.extra`,'num',d.extra)}</td><td class="n">${F('plan',`debts.${i}.day`,'num',d.day,'min="1" max="31" style="width:60px"')}</td><td>${delBtn('plan','debts',i)}</td></tr>`).join('')}</tbody></table></div>
   <div class="row" style="margin-top:8px"><button class="btn ghost sm" data-act="add" data-list="debts">+ Add debt</button><span class="small muted">Balances and starting balances save straight away. Payments, rates and pay days are part of the plan, so they save with the Save plan button.</span></div>
   ${(STATE.lumps||[]).length?`<div class="lbl" style="margin:14px 0 4px">Planned lump sums</div>${STATE.lumps.map((l,i)=>`<div class="item"><span>${esc((p.debts.find(d=>d.id===l.debt)||{}).name||'debt')} on ${fdate(parseISO(l.date))}, from ${l.from==='savings'?'savings':'bank'}</span><span class="row"><b>${GBP(l.amount)}</b>${delBtn('state','lumps',i)}</span></div>`).join('')}`:''}</div></div>`}
function vGoals(){
  const p=draft(),S=fc(),byId=Object.fromEntries(S.goals.map(g=>[g.id,g]));
  const rows=p.goals.map((g0,i)=>{const g=byId[g0.id]||{reqM:0,status:'beyond',pot:0};return`<tr><td>${F('plan',`goals.${i}.name`,'str',g0.name)}</td><td>${SEL('plan',`goals.${i}.kind`,g0.kind||'other',[['holiday','Holiday'],['other','Other']])}</td><td class="n">${F('plan',`goals.${i}.target`,'num',g0.target)}</td><td class="n">${F('state',`goalSaved.${g0.id}`,'num',STATE.goalSaved[g0.id]||0)}</td><td>${F('plan',`goals.${i}.date`,'date',g0.date)}</td><td class="n">${F('plan',`goals.${i}.monthly`,'num',g0.monthly||'','placeholder="auto"')}</td><td class="n">${GBP(g.reqM)}</td><td style="text-align:center">${F('plan',`goals.${i}.amex`,'bool',g0.amex)}</td><td>${g.status==='ok'?'<span class="pill good">on track</span>':g.status==='late'?'<span class="pill bad">short '+GBP(g.gs?g.gs.short:g0.target-g.pot)+'</span>':'<span class="pill warn">not funded in time</span>'}</td><td>${delBtn('plan','goals',i)}</td></tr>`}).join('');
  const hol=sum(p.goals.filter(g=>g.kind==='holiday'&&g.amex),g=>g.target);
  return draftBar()+intro('Holidays and other big events. Set a budget and a date and the app works out how much to put aside each month. The soonest date is funded first, and tax always comes before everything else.')+`
  <div class="kpis"><div class="kpi"><span>Monthly savings transfer</span><b>${GBP(p.savings.monthly)}</b><small>moves on the ${ord(p.savings.day)}</small></div>
   <div class="kpi"><span>Needed per month for all goals</span><b>${GBP(sum(S.goals,g=>g.reqM))}</b><small>including tax</small></div>
   <div class="kpi"><span>Savings in 12 months</span><b>${GBP(S.days[Math.min(364,S.days.length-1)].sav)}</b></div></div>
  <div class="grid"><div class="panel c12"><h2>Goals and holidays</h2>
   <div class="tblwrap"><table><thead><tr><th>Goal</th><th>Type</th><th class="n">Budget £</th><th class="n">Saved so far £</th><th>Needed by</th><th class="n">Fixed £/month</th><th class="n">Needed per month</th><th style="text-align:center">On Amex</th><th>Forecast</th><th></th></tr></thead><tbody>${rows||'<tr><td colspan="10" class="muted">No goals yet. Add your first holiday or event.</td></tr>'}</tbody></table></div>
   <div class="row" style="margin-top:8px"><button class="btn ghost sm" data-act="add" data-list="goals">+ Add holiday or goal</button></div>
   <p class="small muted">The monthly transfer is shared by date: the nearest goal gets what it needs, and the rest builds general savings. Tick "On Amex" to book it by card: the savings move to the bank on the travel date and pay the statement later.${hol?` Holidays booked this way earn about ${Math.round(hol*p.amex.rate).toLocaleString('en-GB')} Avios.`:''}</p></div>
   <div class="panel c6"><h2>Savings settings</h2><div class="list">
    <div class="item"><span>Monthly transfer to savings</span>${F('plan','savings.monthly','num',p.savings.monthly,'style="width:110px"')}</div>
    <div class="item"><span>Day of month it moves</span>${F('plan','savings.day','num',p.savings.day,'min="1" max="28" style="width:80px"')}</div>
    <div class="item"><span>General savings now (no goal)</span>${F('state','general','num',STATE.general||0,'style="width:110px"')}</div></div></div>
   <div class="panel c6"><h2>Are the goals affordable?</h2>${goalsMini(S)}</div></div>`}
function vTax(){
  const p=draft(),S=fc(),byId=Object.fromEntries(S.goals.map(g=>[g.id,g]));
  const rows=p.tax.map((t,i)=>{const g=byId[t.id]||{reqM:0,status:'beyond',pot:0},exp=(t.last||0)*((t.adj??100)/100);
    return`<div class="panel c12"><div class="row" style="justify-content:space-between"><h3>${F('plan',`tax.${i}.name`,'str',t.name,'style="font-weight:700;font-size:1rem;width:min(420px,100%)"')}</h3>${delBtn('plan','tax',i)}</div>
    <div class="grid" style="margin-top:12px"><div class="c4"><div class="lbl">Last year's bill £</div>${F('plan',`tax.${i}.last`,'num',t.last,'style="width:140px;margin:4px 0 10px" placeholder="enter when known"',true)}
      <div class="lbl">Due on</div>${F('plan',`tax.${i}.date`,'date',t.date,'style="margin:4px 0 10px"')}<div class="lbl">Already put aside £</div>${F('state',`taxSaved.${t.id}`,'num',STATE.taxSaved[t.id]||0,'style="width:140px;margin-top:4px"')}</div>
     <div class="c4"><div class="sl"><label for="tx${i}">Expect this year's bill to be</label><output id="o_tx${i}">${pct(t.adj??100)}</output><input type="range" id="tx${i}" data-r="plan" data-p="tax.${i}.adj" data-t="num" data-out="o_tx${i}" min="0" max="200" step="5" value="${t.adj??100}"><span class="hint">of last year's. Below 100% if income is down, above if up.</span></div><div class="lbl">Expected bill</div><div class="big">${t.last==null?'–':GBP(exp)}</div></div>
     <div class="c4"><div class="lbl">Put aside each month</div><div class="big">${GBP(g.reqM)}</div><div class="small ink2" style="margin:4px 0 8px">until ${fdate(parseISO(t.date))}</div>
      ${t.last==null?'<span class="pill warn">Add last year\'s bill</span>':g.status==='ok'?'<span class="pill good">Fully funded in time</span>':g.status==='late'?'<span class="pill bad">Short by '+GBP(g.gs?g.gs.short:exp-g.pot)+'</span>':'<span class="pill warn">Not funded in time</span>'}</div></div></div>`}).join('');
  const total=sum(S.goals.filter(g=>g.kind==='tax'),g=>g.reqM);
  return draftBar()+intro(`Put tax aside every month so the bill is already in savings when it arrives. Start from last year's figure, then move the slider if this year will be different. Tax is funded before holidays and other goals. Until you enter last year's bill, nothing is set aside.`)+`
  <div class="kpis"><div class="kpi"><span>Tax to put aside each month</span><b>${GBP(total)}</b><small>${pct(total/Math.max(1,p.savings.monthly)*100)} of your ${GBP(p.savings.monthly)} monthly savings</small></div></div>
  <div class="grid">${rows||'<div class="panel c12 muted">No tax bills yet.</div>'}<div class="panel c12"><button class="btn ghost" data-act="add" data-list="tax">+ Add a tax bill</button>
   <p class="small muted" style="margin-bottom:0">You said the bill usually lands in April or May, so the date starts at 30 April 2027. [Likely] If this is Self Assessment with payments on account, HMRC may also ask for instalments on 31 January and 31 July, so check your latest HMRC statement and add each payment as its own tax bill.</p></div></div>`}
function vAmex(){
  const p=draft(),S=fc(),A=p.amex,st=S.stmts.slice(0,6),yr=S.cardSpend/S.nMonths*12,pts=yr*A.rate,val=pts*A.pv/100,fees=S.feeTotal/S.nMonths*12;
  return draftBar()+banners()+intro('The Amex is safe as long as the cash to clear it is already set aside. This tab shows each statement, when it is due and whether the bank can pay it.')+`<div class="grid">
   <div class="panel c12" style="border-color:var(--bank)"><b>Note on the two cardholders.</b> The Amex has two cardmembers. Only <b>${esc(amexJointName())}</b>'s spending is joint and counts towards the household budget and what the bank must cover. The other cardholder's spending is personal and is left out when you upload a statement. Change the name in Settings if needed.</div>
   <div class="panel c4"><h2>Safety check</h2><p style="margin:0 0 8px">${verdictPill(S)}</p><p class="ink2" style="margin-top:0">${esc(S.why)}</p>
    <div class="note"><b>The rule:</b> money in the bank that you owe Amex is not yours to spend. The dashed line on the Today chart is your bank balance minus what you owe Amex. Keep it above your buffer and the card cannot put you in debt.</div>
    <div class="list" style="margin-top:10px"><div class="item"><span>Put on Amex</span><b>${p.amexShare||0}% of card-friendly spend</b></div><div class="item"><span>Owed now</span><b>${GBP(amexOwedNow())}</b></div><div class="item"><span>Card spend per year</span><b>${GBP(yr)}</b></div>
     <div class="item"><span>Average days to pay</span><b>${S.float||'–'}</b></div><div class="item"><span>Avios per year</span><b>${Math.round(pts).toLocaleString('en-GB')}</b></div><div class="item"><span>Worth about</span><b>${GBP(val)}</b></div><div class="item"><span>Card fees per year</span><b>${GBP(fees)}</b></div><div class="item"><span>Net gain</span><b class="${val-fees<0?'neg':'pos'}">${GBP(val-fees)}</b></div></div>
    <p class="small muted">If a biller charges more than about ${(A.rate*A.pv).toFixed(1)}% to take a card, the points are worth less than the fee. [Likely] Mortgage lenders rarely take a card directly.</p></div>
   <div class="panel c8"><h2>Statements in your forecast</h2>${st.length?`<div class="tblwrap"><table><thead><tr><th>Statement closes</th><th>You pay (in full)</th><th class="n">Amount</th><th class="n">Bank balance that day</th></tr></thead><tbody>${st.map(s=>{const b=S.days.find(d=>d.t===s.due);return`<tr><td>${fdate(s.close)}</td><td>${fdate(s.due)}</td><td class="n">${GBP(s.amt)}</td><td class="n ${b&&b.bank<s.amt?'neg':''}">${b?GBP(b.bank):'–'}</td></tr>`}).join('')}</tbody></table></div>`:'<p class="muted">No card spend yet. Type spending paid with Amex on Day to day, raise the Amex share on What if, or tick "On Amex" on a bill or holiday.</p>'}
    <p class="small muted">A purchase the day after a statement closes waits about 30 days for the statement and 25 more to pay. That gap is the cashflow benefit. The due date is editable below because yours can vary.</p></div>
   <div class="panel c12"><h2>Card settings</h2><div class="row" style="gap:22px">
    <label>Statement closes on day ${F('plan','amex.closeDay','num',A.closeDay,'min="1" max="28" style="width:64px"')}</label><label>Payment due ${F('plan','amex.dueDays','num',A.dueDays,'min="0" max="60" style="width:64px"')} days after</label>
    <label>Points per £1 ${F('plan','amex.rate','num',A.rate,'step="0.1" style="width:64px"')}</label><label>1 Avios is worth (pence) ${F('plan','amex.pv','num',A.pv,'step="0.1" style="width:64px"')}</label>
    <label>Balance owed on ${F('state','amexOwedDate','date',STATE.amexOwedDate||STATE.startedAt)} £ ${F('state','amexOwed','num',STATE.amexOwed||0,'style="width:90px"')}</label></div>
    <p class="small muted">Your example: spend 6 Aug to 5 Sep was due on 30 Sep, which is 25 days after the statement closed, so 25 is the default. Typed Amex entries after the balance date are added to what you owe.</p></div></div>`}
