/* ===== Guide and Settings ===== */
function vGuide(){
  const done={bank:STATE.bank!=null,debts:curPlan().debts.filter(d=>d.pay>0).every(d=>STATE.debtBal[d.id]!=null),tax:curPlan().tax.every(t=>t.last!=null),goals:curPlan().goals.length>0};
  const st=(ok,n,t,s)=>`<div class="step"><span class="tick ${ok?'done':'todo'}">${ok?'✓':n}</span><div><b>${t}</b> <span class="small muted">${s}</span></div></div>`;
  const tabs=[['Every day',[['Today','Where do we stand right now, and are we on track this month?','Read it. Sort any unsorted payments shown there.','Whenever you like'],['Day to day','What have we spent, and on what?','Type spending or upload a NatWest or Amex file. Sort unsorted lines. Browse every category and its payments.','As you spend, or when you upload'],['Cash and bank','How much cash do we hold, and does the bank add up?','Log cash that comes in, and transfers between the bank and cash. Check the bank balance.','When cash moves']]],
   ['Understand',[['Where it goes','Where does most of our money go, and what could we cut?','Read it. Try the "cut the wants" slider.','Monthly'],['Patterns','What is our history telling us?','Add a note to big payments. Read what has been noticed.','Monthly'],['Plan vs actual','How did each month compare with the plan, or with another period?','Pick a period and compare it. See which bills are paid.','Monthly'],['What if','What happens if we change something?','Move sliders for income, budgets, savings, overpaying or a lump sum. Nothing changes until you press "Make this my plan", and then only from next month.','When deciding'],['Net worth','What are we worth, and is it growing?','Update the house, pensions, vehicles and premium bonds. The rest fills in by itself.','Monthly or quarterly']]],
   ['Commitments',[['Budgets','What do we plan to receive and spend?','Edit wages, fixed bills, yearly bills, variable budgets and transfers. Save from a month. Past months keep their plan.','Only when something changes'],['Debts','What do we owe, and when will it be gone?','Type each balance from its latest statement. Test a lump sum or overpayment.','Monthly'],['Goals and holidays','Can we afford what we are saving for, by when?','Add holidays and events with a budget and a date.','When plans change'],['Tax','How much should we set aside for tax?','Enter last year\'s bill and move the slider for this year.','Yearly, or when income changes'],['Amex','Is the card safe, and what is it earning?','Set statement and due dates. See each statement against your bank balance.','When you start using it']]],
   ['Help and settings',[['Guide','What does this mean?','This page.','Any time'],['Settings','How strict are the flags, and where is my data?','Set the buffer and the big-payment limit. See what history is loaded. Back up your data.','Rarely']]]];
  return intro('Read this once. It explains every tab, what the colours and labels mean, and what to do first. Nothing here changes your figures.')+`<div class="grid">
   <div class="panel c12"><h2>Start here: four things to enter first</h2><p class="small ink2" style="margin-top:0">The app works with nothing entered, but it only becomes useful once these are in. Ticks appear by themselves.</p>
    ${st(done.bank,1,"Today's bank balance",'Cash and bank tab, or upload a NatWest file on Day to day.')}${st(done.debts,2,'Balances on your debts','Debts tab: mortgage, MBNA, Ikea, tax plan. Type them whenever you find them.')}${st(done.tax,3,"Last year's tax bill",'Tax tab. Until then nothing is set aside for tax.')}${st(done.goals,4,'Your savings goals and holidays','Goals and holidays tab: name, budget, date. Also add your yearly bills (such as December insurance) on Budgets.')}</div>
   <div class="panel c12"><h2>What each tab is for</h2><div class="tblwrap"><table><thead><tr><th>Tab</th><th>The question it answers</th><th>What you do there</th><th>How often</th></tr></thead><tbody>${tabs.map(([g,rs])=>`<tr class="grp"><td colspan="4">${g}</td></tr>`+rs.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td></tr>`).join('')).join('')}</tbody></table></div></div>
   <div class="panel c12"><h2>How the tabs connect</h2><div class="flow"><div class="col"><b>You enter</b><span class="small ink2">Budgets: wages, bills, budgets, transfers<br>Debts: balances and payments<br>Goals and holidays, Tax<br>Day to day: spending<br>Cash and bank: cash and transfers<br>Net worth: house, pensions</span></div><div class="arrow">→</div><div class="col"><b>It works out</b><span class="small ink2">Your bank balance, day by day, for two years<br>How much to save for each goal<br>When each debt ends<br>Whether the Amex is safe<br>Patterns in your history</span></div><div class="arrow">→</div><div class="col"><b>You read</b><span class="small ink2">Today: where you stand<br>Where it goes: what to cut<br>Plan vs actual: how a month went<br>What if: what a change would do<br>Net worth: are we growing</span></div></div>
    <p class="small muted" style="margin-bottom:0">Real spending is compared with the plan. The plan only changes when you save changes on Budgets or press "Make this my plan", and never for a past month.</p></div>
   <div class="panel c6"><h2>Colours and labels</h2><div class="list">
    <div class="item"><span><b class="sw" style="display:inline-block;width:12px;height:12px;border-radius:3px;background:var(--need);margin-right:8px"></b>Blue</span><span class="small ink2 l" style="text-align:right">Your bank balance, and things you need</span></div>
    <div class="item"><span><b class="sw" style="display:inline-block;width:12px;height:12px;border-radius:3px;background:var(--want);margin-right:8px"></b>Orange</span><span class="small ink2 l" style="text-align:right">Wants, and bills on charts</span></div>
    <div class="item"><span><b class="sw" style="display:inline-block;width:12px;height:12px;border-radius:3px;background:var(--debt);margin-right:8px"></b>Violet</span><span class="small ink2 l" style="text-align:right">Debts and the Amex</span></div>
    <div class="item"><span><b class="sw" style="display:inline-block;width:12px;height:12px;border-radius:3px;background:var(--save);margin-right:8px"></b>Teal</span><span class="small ink2 l" style="text-align:right">Savings and net worth</span></div>
    <div class="item"><span><span class="pill good">On track</span> <span class="pill warn">Tight</span> <span class="pill bad">Short</span></span><span class="small ink2 l" style="text-align:right">Green is fine, amber needs a look, red needs action</span></div>
    <div class="item"><span><span class="ex" style="margin:0">CHECK DAY</span></span><span class="small ink2 l" style="text-align:right">A bill day that wasn't on your sheet. Confirm it.</span></div>
    <div class="item"><span><span class="chip mv">Expected</span> <span class="chip in">✓ Paid</span></span><span class="small ink2 l" style="text-align:right">Whether a bill has come out of the bank yet</span></div></div></div>
   <div class="panel c6"><h2>Words used</h2><div class="list">
    ${[['Left over','What remains before the next wages after all planned bills, remaining budgets, what you owe Amex and your buffer.'],['Buffer','The minimum you want left in the bank at all times.'],['Bank check','The balance you type or upload, minus what your entries say it should be. Matches means it all adds up.'],['Budget pace','Your month\'s budget spread evenly by day. Over it means ahead of plan.'],['Unsorted','Spending with no category yet. It still counts in your total.'],['Household cash','The shared cash pot. Not the same as Annie\'s and Sander\'s spending money, which is a transfer.'],['Plan version','A saved set of budgets that applies from a month onward. Past months keep theirs.'],['Snapshot','A saved net worth figure, one a month.']].map(([a,b])=>`<div class="item"><span class="l"><b>${a}</b></span><span class="small ink2 l" style="text-align:right">${b}</span></div>`).join('')}</div></div>
  </div>`}
function vSettings(){
  const ak=actualKeys(),cats=allVars();
  return intro('How strict the flags are, what history is loaded, and a backup of your data.')+`<div class="grid">
   <div class="panel c6"><h2>Flags and safety</h2><div class="list">
    <div class="item"><span>Safety buffer to keep in the bank</span>${F('state','buffer','num',STATE.buffer,'style="width:100px"')}</div>
    <div class="item"><span>Flag any payment over £</span>${F('state','flagLimit','num',STATE.flagLimit,'style="width:100px"')}</div></div>
    <div class="lbl" style="margin:14px 0 6px">Don't flag payments in these categories</div>
    <div class="row" style="gap:6px 16px">${cats.map(v=>`<label class="small" style="display:flex;gap:6px;align-items:center"><input type="checkbox" data-act="flagexcl" data-v="${v.id}" ${(STATE.flagExcl||[]).includes(v.id)?'checked':''}> ${esc(v.name)}</label>`).join('')}</div>
    <p class="small muted">Shopping is left out by default so a weekly food shop doesn't ask for a note every time.</p></div>
   <div class="panel c6"><h2>History</h2>${ak.length?`<p style="margin-top:0"><b>${ak.length} months</b> loaded from your sheet, ${fmonth(ak[0])} to ${fmonth(ak[ak.length-1])}.</p><p class="small muted">${histKeys().filter(k=>!normHist(k).hasActual).length?'Months without actual figures: '+histKeys().filter(k=>!normHist(k).hasActual).map(fmonth).join(', ')+'. ':''}September 2023 is missing from the sheet itself. Categories are tidied from your sheet's own names (for example Takeout, Restaurants and Takeout/Entertainment all become Takeout / Restaurants / Entertainment).</p>`:'<p class="muted" style="margin-top:0">No history is loaded in this copy.</p>'}
    <div class="lbl" style="margin:12px 0 6px">Who is using this</div><p class="small">${ME.name?esc(ME.name):'Name not available'} ${dbh?'· shared copy':'· this device only'}</p></div>
   <div class="panel c12"><h2>Backup</h2><p class="small ink2" style="margin-top:0">A copy of your plan, entries and balances (not your sheet history). Paste it back to restore.</p>
    <div class="row"><button class="btn ghost" data-act="backup">Show backup</button><button class="btn ghost" data-act="restore">Restore from the box below</button><button class="btn danger" data-act="resetall">Erase everything on this device</button></div>
    <textarea id="bk" style="width:100%;height:120px;margin-top:10px;font-family:ui-monospace,monospace;font-size:.78rem" placeholder="Backup text appears here, or paste a backup to restore"></textarea></div>
  </div>`}
